services:
  - type: web
    name: medivision
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn medivision.wsgi --timeout 120 --workers 1
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO
        value: DeepakLPU/medivision-models
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
    disk:
      name: models-disk
      mountPath: /opt/render/project/src/ml_models
      sizeGB: 5