# Generated by Django 6.0.5 on 2026-05-19 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_key', models.CharField(max_length=64)),
                ('scan_title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('predicted_class', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('high', 'High Risk'), ('critical', 'Critical')], max_length=20)),
                ('advice', models.TextField()),
                ('demo_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
